addons: {}
after_success:
- export JAVA_TOOL_OPTIONS=-javaagent:$DFB_PROJECT_DIR/jacoco-agent-jdk8.jar=destfile=$DFB_PROJECT_DIR/jacoco.exec
- mvn test -Djacoco.skip=true -Dcobertura.skip=true -Dmaven.clover.skip=true test
- ./df-build.sh
- env > env.file
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install |
  bash
- artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket
  $DFB_AWS_BUCKET --target-paths $DFB_AWS_BUILD_PATH $(git ls-files -oi -x *.exec)
- artifacts upload --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --bucket
  $DFB_AWS_BUCKET --target-paths $DFB_AWS_BUILD_PATH ${DFB_PROJECT_DIR}/env.file
android:
  components:
  - build-tools-20.0.0
  - android-17
  licenses:
  - android-sdk-license-5be876d5
before_install:
- wget -O beforebuild.sh $DFB_AGENTS_URL/beforebuild.sh
- chmod a+x beforebuild.sh
- ./beforebuild.sh
branches:
  except:
  - gh-pages
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: K6cyrlYhMmCHeez4uwkcQ5QeRLdCiegbbHnj8qKzbgcu0cDsvr2mMr6LLtjMOay1KMaxrW3QBFqz5nzTs/X0UnLl8jnt0Qdsf44BlIIZcJ9oldXFKAAWUZ3wlHTdz8ll+EBA31O1hkjAqRY4RDvS1hk842pRxXae3Dfodnjhz24=
  - secure: pOUA/hwXvpwt7VeRIoAZPiIn2qc88c8/sx1AhN3YhSyCiERLEtuxZqFmCgZE/80U41sBlvg75lpvXpEsND4eriYiRNMDPyD7el2NYxTzseWAykZYe1+Gaeiq1mO83w4pTI7QUrrkU/9+rl9Ccqe6E0heER510ERyLH0nGb8vaRM=
  - DFB_PROJECT_DIR=$(pwd)
  - TMP_PROJECT_PARENT_DIR=$(dirname $DFB_PROJECT_DIR)
  - DFB_BUILD_ID=$TRAVIS_BUILD_ID
  - DFB_PRODUCT_NAME=$(basename $DFB_PROJECT_DIR)
  - DFB_OWNER_NAME=$(basename $TMP_PROJECT_PARENT_DIR)
  - DFB_PRODUCT_KEY=${DFB_OWNER_NAME}_${DFB_PRODUCT_NAME}
  - DFB_AWS_BUCKET=aline-external-ci-artifacts
  - DFB_AGENTS_URL=https://s3.amazonaws.com/${DFB_AWS_BUCKET}/agents
  - DFB_PACKAGING_URL=s3://${DFB_AWS_BUCKET}/artifacts/travis/
  - DFB_AWS_BUILD_PATH=/artifacts/travis/${DFB_PRODUCT_KEY}/${DFB_BUILD_ID}/output/
  - AWS_ACCESS_KEY_ID=AKIAIIU2LBOCCKXAIFZQ
  - AWS_SECRET_ACCESS_KEY=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
  - DFB_JTO=-javaagent:${DFB_PROJECT_DIR}/dfbuild-agent.jar=PACKAGING_BASE_URI=$DFB_PACKAGING_URL,PRODUCT_KEY=$DFB_PRODUCT_KEY/,BUILD_KEY=$DFB_BUILD_ID/,MODULES_KEY=modules/,START_TIME=0,BUILD_BASE_DIR=$DFB_PROJECT_DIR
install: 'true'
jdk:
- oraclejdk8
language: android
notifications: {}
script:
- export JAVA_TOOL_OPTIONS=$DFB_JTO
- mvn -Djacoco.skip=true -Dcobertura.skip=true -Dmaven.clover.skip=true test
sudo: false
# Modified by IntegrationTestInstrumentation at 2016-05-14 05:35:08.932103
